//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForbiddenBookshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.DisappearedReaders = new HashSet<DisappearedReaders>();
            this.OrderBooks = new HashSet<OrderBooks>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> CurseLevel { get; set; }
        public string Language { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DisappearedReaders> DisappearedReaders { get; set; }
        public virtual ICollection<OrderBooks> OrderBooks { get; set; }
    }
}
