//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForbiddenBookshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.DisappearedReaders = new HashSet<DisappearedReaders>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MadnessLevel { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<DisappearedReaders> DisappearedReaders { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
