//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForbiddenBookshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Customers = new HashSet<Customers>();
            this.Keepers = new HashSet<Keepers>();
            this.Logs = new HashSet<Logs>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public int RoleID { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Customers> Customers { get; set; }
        public virtual ICollection<Keepers> Keepers { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
